(defun do-create-binding (args)
  (let* ((gen-dir (first args))
         (templates-dir (second args))
         (target (third args))
         (data (directory
            (merge-pathnames (pathname gen-dir)
                (pathname "*.lsp"))))
         (templates (directory (merge-pathnames (pathname templates-dir)
                (pathname "*.dj"))))
         (target-path (pathname target)))
    (princ "Make ECL binding")
    (princ data)
    (princ templates)
    (princ target-path)))
