;;
;; libBeresta
;;
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025-2026
;;

(in-package #:cl-beresta)

(include-header)

(synonym Annotation Dict)

(enum AnnotType (
  ANNOT-TEXT
  ANNOT-LINK
  ANNOT-FREE-TEXT
  ANNOT-LINE
  ANNOT-SQUARE
  ANNOT-CIRCLE
  ANNOT-POLYGON
  ANNOT-POLYLINE
  ANNOT-HIGHLIGHT
  ANNOT-UNDERLINE
  ANNOT-SQUIGGLY
  ANNOT-STRIKEOUT
  ANNOT-STAMP
  ANNOT-CARET
  ANNOT-INK
  ANNOT-POPUP
  ANNOT-FILE-ATTACHMENT
  ANNOT-SOUND
  ANNOT-MOVIE
  ANNOT-WIDGET
  ANNOT-SCREEN
  ANNOT-PRINTER-MARK
  ANNOT-TRAPNET
  ANNOT-WATERMARK
  ANNOT-3D
  ANNOT-REDACT
))

(enum AnnotFlags (
  ANNOT-FLAG-INVISIBLE
  ANNOT-FLAG-HIDDEN
  ANNOT-FLAG-PRINT
  ANNOT-FLAG-NOZOOM
  ANNOT-FLAG-NOROTATE
  ANNOT-FLAG-NOVIEW
  ANNOT-FLAG-READONLY
  ANNOT-FLAG-LOCKED
  ANNOT-FLAG-TOGGLE-NOVIEW
  ANNOT-FLAG-LOCKED-CONTENT
))

(enum AnnotHighlightMode (
  ANNOT-HIGHLIGHT-MODE-NONE
  ANNOT-HIGHLIGHT-MODE-INVERT
  ANNOT-HIGHLIGHT-MODE-OUTLINE
  ANNOT-HIGHLIGHT-MODE-PUSH
))

(enum AnnotIcon (
  ANNOT-ICON-COMMENT
  ANNOT-ICON-KEY
  ANNOT-ICON-NOTE
  ANNOT-ICON-HELP
  ANNOT-ICON-NEW-PARAGRAPH
  ANNOT-ICON-PARAGRAPH
  ANNOT-ICON-INSERT
))

(enum AnnotLineEnd (
  ANNOT-LINE-END-NONE
  ANNOT-LINE-END-SQUARE
  ANNOT-LINE-END-CIRCLE
  ANNOT-LINE-END-DIAMOND
  ANNOT-LINE-END-OPENARROW
  ANNOT-LINE-END-CLOSEDARROW
  ANNOT-LINE-END-BUTT
  ANNOT-LINE-END-ROPENARROW
  ANNOT-LINE-END-RCLOSEDARROW
  ANNOT-LINE-END-SLASH
))

(enum AnnotLineCapPosition (
  ANNOT-LINE-CAP-INLINE
  ANNOT-LINE-CAP-TOP
))

(enum AnnotStampStyle (
  ANNOT-STAMP-APPROVED
  ANNOT-STAMP-EXPERIMENTAL
  ANNOT-STAMP-NOTAPPROVED
  ANNOT-STAMP-ASIS
  ANNOT-STAMP-EXPIRED
  ANNOT-STAMP-NOTFORPUBLICRELEASE
  ANNOT-STAMP-CONFIDENTIAL
  ANNOT-STAMP-FINAL
  ANNOT-STAMP-SOLD
  ANNOT-STAMP-DEPARTMENTAL
  ANNOT-STAMP-FORCOMMENT
  ANNOT-STAMP-TOPSECRET
  ANNOT-STAMP-DRAFT
  ANNOT-STAMP-FORPUBLICRELEASE
))
