;;
;; libBeresta
;;
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025-2026
;;

(in-package #:cl-user)

(defpackage #:cl-beresta
  (:use #:cl)
  (:nicknames :brst)
  (:export

 ;; Pointers
 ;; ========

  ;; array.lsp
  #:Array

  ;; date.lsp
  #:Date

  ;; dict.lsp
  #:Dict

  ;; doc.lsp
  #:Doc

  ;; error.lsp
  #:Error

  ;; fontdef.lsp
  #:FontDef

  ;; matrix.lsp
  #:Matrix

  ;; mmgr.lsp
  #:MMgr

  ;; stream.lsp
  #:Stream

  ;; xref.lsp
  #:Xref

 ;; Constants
 ;; =========

  ;; consts.lsp
  #:MM
  #:IN
  #:PI
  #:TRUE
  #:OK
  #:FALSE

  ;; Functions
  ;; =========

  ;; asian.lsp
  #:UseJPEncodings
  #:UseCNSEncodings
  #:UseKREncodings
  #:UseJPFonts
  #:UseCNTFonts
  #:UseCNTEncodings
  #:UseCNSFonts
  #:UseKRFonts

  ;; base.lsp
  #:PageSize-Width
  #:Doc-Destroy-All
  #:Doc-Destroy
  #:Doc-Initialized
  #:Doc-Free
  #:Version
  #:PageSize-Height
  #:Doc-New-Empty
  #:Doc-New-Ex
  #:Doc-New
  #:Doc-MMgr
  #:Doc-Initialize

  ;; date.lsp
  #:Date-Free
  #:Date-Part
  #:Date-Validate
  #:Date-Now

  ;; destination.lsp
  #:Destination-SetFitH
  #:Destination-SetFitBH
  #:Destination-SetFitB
  #:Destination-SetFitR
  #:Destination-SetFitV
  #:Destination-SetFit
  #:Destination-SetFitBV
  #:Destination-SetXYZ

  ;; doc_compression.lsp
  #:Doc-SetCompressionMode

  ;; doc_embedded_file.lsp
  #:Doc-AttachFile

  ;; doc_encoder.lsp
  #:Doc-Encoder-SetCurrent
  #:Doc-Encoder-Current
  #:Doc-Encoder-Prepare

  ;; doc_encoding_utf.lsp
  #:Doc-UseUTFEncodings

  ;; doc_ext_gstate.lsp
  #:Doc-Create-ExtGState

  ;; doc_font.lsp
  #:Doc-Type1Font-LoadFromFile
  #:Doc-TTFont-LoadFromFile
  #:Doc-Font
  #:Doc-TTFont-LoadFromMemory
  #:Doc-TTFont-LoadFromFile2

  ;; doc_image_jpeg.lsp
  #:Doc-Image-Jpeg-LoadFromMemory
  #:Doc-Image-Jpeg-LoadFromFile

  ;; doc_image_png.lsp
  #:Doc-Image-Png-LoadFromFile2
  #:Doc-Image-Png-LoadFromFile
  #:Doc-Image-Png-LoadFromMemory

  ;; doc_image_tiff.lsp
  #:Doc-Image-Raw-LoadFromMemory
  #:Doc-Image-Raw-LoadFromFile
  #:Doc-Image-Raw1Bit-LoadFromMemory

  ;; doc_info.lsp
  #:Doc-SetInfoAttr
  #:Doc-SetInfoDateAttr

  ;; doc_matrix.lsp
  #:Doc-Matrix-Skew
  #:Doc-Matrix-Translate
  #:Doc-Matrix-RotateDeg
  #:Doc-Matrix-Identity
  #:Doc-Matrix-Scale
  #:Doc-Matrix-Multiply
  #:Doc-Matrix-Free
  #:Doc-Matrix-Rotate

  ;; doc_output_intent.lsp
  #:Doc-OutputIntent-Add
  #:Doc-OutputIntent-New

  ;; doc_page.lsp
  #:Doc-Page-AddLabel
  #:Doc-Page-Layout
  #:Doc-Page-Add
  #:Doc-Page-SetLayout
  #:Doc-Page-ByIndex
  #:Doc-Page-Current
  #:Doc-Page-Mode
  #:Doc-Page-Insert
  #:Doc-Page-SetMode
  #:Doc-Pages-SetConfiguration

  ;; doc_page_pattern.lsp
  #:Doc-Dict-RGBPatternFill-Select
  #:Doc-Page-RGBPatternFill-Select
  #:Doc-Dict-RGBPatternFillUint-Select
  #:Doc-Dict-RGBPatternFillHex-Select
  #:Doc-Page-RGBPatternFillHex-Select
  #:Doc-Page-RGBPatternFillUint-Select

  ;; doc_pattern.lsp
  #:Doc-Pattern-Tiling-Create
  #:Doc-Pattern-Stream

  ;; doc_pdfa.lsp
  #:Doc-PDFA-SetConformance
  #:Doc-PDFA-AddXmpExtension
  #:Doc-PDFA-AppendOutputIntents

  ;; doc_save.lsp
  #:Doc-SaveToStream
  #:Doc-SaveToFile

  ;; doc_security.lsp
  #:Doc-SetPassword
  #:Doc-SetEncryptionMode
  #:Doc-SetPermission

  ;; doc_viewer.lsp
  #:Doc-ViewerPreference
  #:Doc-SetViewerPreference
  #:Doc-SetOpenAction

  ;; doc_xobject.lsp
  #:Doc-XObject-CreateAsWhiteRect
  #:Doc-XObject-CreateFromImage
  #:Doc-XObject-Create

  ;; error.lsp
  #:Doc-Error-SetHandler
  #:Doc-Error-DetailCode
  #:Doc-Error-Reset
  #:Doc-Error-Code
  #:Error-Check

  ;; ext_gstate.lsp
  #:ExtGState-SetBlendMode
  #:ExtGState-SetAlphaFill
  #:ExtGState-SetAlphaStroke

  ;; font.lsp
  #:Font-Descent
  #:Font-TextWidth2

  ;; geometry.lsp
  #:Page-Arc
  #:Page-SetRGBStrokeUint
  #:Page-CurveTo3
  #:Page-FillColorSpace
  #:Page-MoveTo
  #:Page-Ellipse
  #:Page-LineJoin
  #:Page-Concat
  #:Page-Eoclip
  #:Page-LineTo
  #:Page-SetLineCap
  #:Page-LineWidth
  #:Page-ClosePath
  #:Page-SetRGBFillUint
  #:Page-EofillStroke
  #:Page-GrayFill
  #:Page-SetDash
  #:Page-SetRGBStrokeHex
  #:Page-ClosePathEofillStroke
  #:Page-Skew
  #:Page-GRestore
  #:Page-CurveTo
  #:Page-Scale
  #:Page-FillStroke
  #:Page-LineCap
  #:Page-SetGrayStroke
  #:Page-Translate
  #:Page-SetLineJoin
  #:Page-GSave
  #:Page-EndPath
  #:Page-StrokeColorSpace
  #:Page-ClosePathStroke
  #:Page-Flat
  #:Page-Matrix
  #:Page-ClosePathFillStroke
  #:Page-CurveTo2
  #:Page-SetLineWidth
  #:Page-SetCMYKStroke
  #:Page-Rectangle
  #:Page-SetMiterLimit
  #:Page-SetCMYKFill
  #:Page-Stroke
  #:Page-SetFlat
  #:Page-Circle
  #:Page-SetRGBStroke
  #:Page-SetRGBFill
  #:Page-SetRGBFillHex
  #:Page-MiterLimit
  #:Page-Eofill
  #:Page-RotateDeg
  #:Page-Fill
  #:Page-Rotate
  #:Page-GrayStroke
  #:Page-Clip
  #:Page-SetGrayFill

  ;; page_routines.lsp
  #:Page-SetExtGState
  #:Page-MMgr
  #:Page-Width
  #:Page-SetRotate
  #:Page-HorizontalScaling
  #:Page-CreateDestination
  #:Page-RawWrite
  #:Page-SetSlideShow
  #:Page-SetBoundary
  #:Page-SetHorizontalScaling
  #:Page-GMode
  #:Page-Insert-Shared-Content-Stream
  #:Page-SetHeight
  #:Page-GStateDepth
  #:Page-Height
  #:Page-SetZoom
  #:Page-SetSize
  #:Page-SetWidth

  ;; page_xobject.lsp
  #:Dict-XObject-Execute
  #:Page-XObject-Execute

  ;; stream_geometry.lsp
  #:Stream-FillStroke
  #:Stream-SetGrayFill
  #:Stream-Rectangle
  #:Stream-GSave
  #:Stream-SetCMYKFill
  #:Stream-SetRGBFillUint
  #:Stream-Rotate
  #:Stream-EofillStroke
  #:Stream-CurveTo
  #:Stream-Concat
  #:Stream-Fill
  #:Stream-ClosePathFillStroke
  #:Stream-SetRGBFill
  #:Stream-SetCMYKStroke
  #:Stream-ClosePath
  #:Stream-SetGrayStroke
  #:Stream-CurveTo2
  #:Stream-SetDash
  #:Stream-RotateDeg
  #:Stream-CurveTo3
  #:Stream-SetLineCap
  #:Stream-SetFlat
  #:Stream-Eoclip
  #:Stream-Circle
  #:Stream-SetRGBStrokeUint
  #:Stream-Scale
  #:Stream-GRestore
  #:Stream-LineTo
  #:Stream-MoveTo
  #:Stream-ClosePathEofillStroke
  #:Stream-SetLineWidth
  #:Stream-Eofill
  #:Stream-SetRGBStrokeHex
  #:Stream-SetLineJoin
  #:Stream-Translate
  #:Stream-ClosePathStroke
  #:Stream-SetRGBFillHex
  #:Stream-SetMiterLimit
  #:Stream-Stroke
  #:Stream-Skew
  #:Stream-EndPath
  #:Stream-SetRGBStroke
  #:Stream-Clip

  ;; stream_text.lsp
  #:Stream-SetTextMatrix
  #:Stream-TextOut
  #:Stream-MoveTextPos2
  #:Stream-SetTextRenderingMode
  #:Stream-BeginText
  #:Stream-ShowText
  #:Stream-MoveToNextLine
  #:Stream-SetTextLeading
  #:Stream-EndText
  #:Stream-MoveTextPos

  ;; text.lsp
  #:Page-TextOut
  #:Page-TextWidth
  #:Page-ShowText
  #:Page-WordSpace
  #:Page-SetTextRise
  #:Page-SetFontAndSize
  #:Page-MeasureText
  #:Page-MoveTextPos2
  #:Page-CharSpace
  #:Page-TextMatrix
  #:Page-CurrentFontSize
  #:Page-SetCharSpace
  #:Page-EndText
  #:Page-TextLeading
  #:Page-MoveToNextLine
  #:Page-ShowTextNextLineEx
  #:Page-SetTextLeading
  #:Page-TextRect
  #:Page-TextRenderingMode
  #:Page-CurrentFont
  #:Dict-SetFontAndSize
  #:Page-MoveTextPos
  #:Page-CurrentTextPos2
  #:Page-SetTextMatrix
  #:Page-ShowTextNextLine
  #:Page-SetWordSpace
  #:Page-TextRise
  #:Page-BeginText
  #:Page-SetTextRenderingMode

  ;; unicode_glyph.lsp
  #:GlyphNameToUnicode
  #:UnicodeToGlyphName

  ;; xobject.lsp
  #:XObject-Stream

  ;; Enums
  ;; =====

  ;; annotation.lsp
  ;; AnnotLineEnd
  #:ANNOT-LINE-END-NONE
  #:ANNOT-LINE-END-SQUARE
  #:ANNOT-LINE-END-CIRCLE
  #:ANNOT-LINE-END-DIAMOND
  #:ANNOT-LINE-END-OPENARROW
  #:ANNOT-LINE-END-CLOSEDARROW
  #:ANNOT-LINE-END-BUTT
  #:ANNOT-LINE-END-ROPENARROW
  #:ANNOT-LINE-END-RCLOSEDARROW
  #:ANNOT-LINE-END-SLASH

  ;; annotation.lsp
  ;; AnnotStampStyle
  #:ANNOT-STAMP-APPROVED
  #:ANNOT-STAMP-EXPERIMENTAL
  #:ANNOT-STAMP-NOTAPPROVED
  #:ANNOT-STAMP-ASIS
  #:ANNOT-STAMP-EXPIRED
  #:ANNOT-STAMP-NOTFORPUBLICRELEASE
  #:ANNOT-STAMP-CONFIDENTIAL
  #:ANNOT-STAMP-FINAL
  #:ANNOT-STAMP-SOLD
  #:ANNOT-STAMP-DEPARTMENTAL
  #:ANNOT-STAMP-FORCOMMENT
  #:ANNOT-STAMP-TOPSECRET
  #:ANNOT-STAMP-DRAFT
  #:ANNOT-STAMP-FORPUBLICRELEASE

  ;; annotation.lsp
  ;; AnnotIcon
  #:ANNOT-ICON-COMMENT
  #:ANNOT-ICON-KEY
  #:ANNOT-ICON-NOTE
  #:ANNOT-ICON-HELP
  #:ANNOT-ICON-NEW-PARAGRAPH
  #:ANNOT-ICON-PARAGRAPH
  #:ANNOT-ICON-INSERT

  ;; annotation.lsp
  ;; AnnotLineCapPosition
  #:ANNOT-LINE-CAP-INLINE
  #:ANNOT-LINE-CAP-TOP

  ;; annotation.lsp
  ;; AnnotType
  #:ANNOT-TEXT
  #:ANNOT-LINK
  #:ANNOT-FREE-TEXT
  #:ANNOT-LINE
  #:ANNOT-SQUARE
  #:ANNOT-CIRCLE
  #:ANNOT-POLYGON
  #:ANNOT-POLYLINE
  #:ANNOT-HIGHLIGHT
  #:ANNOT-UNDERLINE
  #:ANNOT-SQUIGGLY
  #:ANNOT-STRIKEOUT
  #:ANNOT-STAMP
  #:ANNOT-CARET
  #:ANNOT-INK
  #:ANNOT-POPUP
  #:ANNOT-FILE-ATTACHMENT
  #:ANNOT-SOUND
  #:ANNOT-MOVIE
  #:ANNOT-WIDGET
  #:ANNOT-SCREEN
  #:ANNOT-PRINTER-MARK
  #:ANNOT-TRAPNET
  #:ANNOT-WATERMARK
  #:ANNOT-3D
  #:ANNOT-REDACT

  ;; annotation.lsp
  ;; AnnotHighlightMode
  #:ANNOT-HIGHLIGHT-MODE-NONE
  #:ANNOT-HIGHLIGHT-MODE-INVERT
  #:ANNOT-HIGHLIGHT-MODE-OUTLINE
  #:ANNOT-HIGHLIGHT-MODE-PUSH

  ;; annotation.lsp
  ;; AnnotFlags
  #:ANNOT-FLAG-INVISIBLE
  #:ANNOT-FLAG-HIDDEN
  #:ANNOT-FLAG-PRINT
  #:ANNOT-FLAG-NOZOOM
  #:ANNOT-FLAG-NOROTATE
  #:ANNOT-FLAG-NOVIEW
  #:ANNOT-FLAG-READONLY
  #:ANNOT-FLAG-LOCKED
  #:ANNOT-FLAG-TOGGLE-NOVIEW
  #:ANNOT-FLAG-LOCKED-CONTENT

  ;; consts.lsp
  ;; CompressionMode
  #:COMP-MODE-NONE
  #:COMP-MODE-TEXT
  #:COMP-MODE-IMAGE
  #:COMP-MODE-METADATA
  #:COMP-MODE-ALL

  ;; consts.lsp
  ;; ViewerPreference
  #:HIDE-TOOLBAR
  #:HIDE-MENUBAR
  #:HIDE-WINDOW-UI
  #:FIT-WINDOW
  #:CENTER-WINDOW
  #:PRINT-SCALING-NONE
  #:DISPLAY-DOC-TITLE

  ;; consts.lsp
  ;; GMode
  #:GMODE-PAGE-DESCRIPTION
  #:GMODE-PATH-OBJECT
  #:GMODE-TEXT-OBJECT
  #:GMODE-CLIPPING-PATH
  #:GMODE-SHADING
  #:GMODE-INLINE-IMAGE
  #:GMODE-EXTERNAL-OBJECT

  ;; consts.lsp
  ;; Permission
  #:ENABLE-READ
  #:ENABLE-PRINT
  #:ENABLE-EDIT-ALL
  #:ENABLE-COPY
  #:ENABLE-EDIT

  ;; date.lsp
  ;; Date_Parts
  #:DATE-PART-YEAR
  #:DATE-PART-MONTH
  #:DATE-PART-DAY
  #:DATE-PART-HOUR
  #:DATE-PART-MINUTE
  #:DATE-PART-SECOND
  #:DATE-PART-HOUR-OFFSET
  #:DATE-PART-MINUTE-OFFSET
  #:DATE-PART-UT-RELATIONSHIP

  ;; date.lsp
  ;; UT_Relationship
  #:UT-RELATIONSHIP-NONE
  #:UT-RELATIONSHIP-PLUS
  #:UT-RELATIONSHIP-MINUS
  #:UT-RELATIONSHIP-ZERO

  ;; doc.lsp
  ;; PdfVer
  #:VER-10
  #:VER-11
  #:VER-12
  #:VER-13
  #:VER-14
  #:VER-15
  #:VER-16
  #:VER-17
  #:VER-20

  ;; doc_info.lsp
  ;; InfoType
  #:INFO-CREATION-DATE
  #:INFO-MOD-DATE
  #:INFO-AUTHOR
  #:INFO-CREATOR
  #:INFO-PRODUCER
  #:INFO-TITLE
  #:INFO-SUBJECT
  #:INFO-KEYWORDS
  #:INFO-TRAPPED
  #:INFO-GTS-PDFX

  ;; encrypt.lsp
  ;; EncryptMode
  #:ENCRYPT-R0
  #:ENCRYPT-R1
  #:ENCRYPT-R2
  #:ENCRYPT-R3
  #:ENCRYPT-R4

  ;; error.lsp
  ;; ErrorKind
  #:ARRAY-COUNT-ERR
  #:ARRAY-ITEM-NOT-FOUND
  #:ARRAY-ITEM-UNEXPECTED-TYPE
  #:BINARY-LENGTH-ERR
  #:CANNOT-GET-PALETTE
  #:DICT-COUNT-ERR
  #:DICT-ITEM-NOT-FOUND
  #:DICT-ITEM-UNEXPECTED-TYPE
  #:DICT-STREAM-LENGTH-NOT-FOUND
  #:DOC-ENCRYPTDICT-NOT-FOUND
  #:DOC-INVALID-OBJECT
  #:DUPLICATE-REGISTRATION
  #:EXCEED-JWW-CODE-NUM-LIMIT
  #:ENCRYPT-INVALID-PASSWORD
  #:ERR-UNKNOWN-CLASS
  #:EXCEED-GSTATE-LIMIT
  #:FAILED-TO-ALLOC-MEM
  #:FILE-IO-ERROR
  #:FILE-OPEN-ERROR
  #:FONT-EXISTS
  #:FONT-INVALID-WIDTH-TABLE
  #:INVALID-AFM-HEADER
  #:INVALID-ANNOTATION
  #:INVALID-BIT-PER-COMPONENT
  #:INVALID-CHAR-MATRIX-DATA
  #:INVALID-COLOR-SPACE
  #:INVALID-COMPRESSION-MODE
  #:INVALID-DATE-TIME
  #:INVALID-DESTINATION
  #:INVALID-DOCUMENT
  #:INVALID-DOCUMENT-STATE
  #:INVALID-ENCODER
  #:INVALID-ENCODER-TYPE
  #:INVALID-ENCODING-NAME
  #:INVALID-ENCRYPT-KEY-LEN
  #:INVALID-FONTDEF-DATA
  #:INVALID-FONTDEF-TYPE
  #:INVALID-FONT-NAME
  #:INVALID-IMAGE
  #:INVALID-JPEG-DATA
  #:INVALID-N-DATA
  #:INVALID-OBJECT
  #:INVALID-OBJ-ID
  #:INVALID-OPERATION
  #:INVALID-OUTLINE
  #:INVALID-PAGE
  #:INVALID-PAGES
  #:INVALID-PARAMETER
  #:INVALID-PNG-IMAGE
  #:INVALID-STREAM
  #:MISSING-FILE-NAME-ENTRY
  #:INVALID-TTC-FILE
  #:INVALID-TTC-INDEX
  #:INVALID-WX-DATA
  #:ITEM-NOT-FOUND
  #:LIBPNG-ERROR
  #:NAME-INVALID-VALUE
  #:NAME-OUT-OF-RANGE
  #:PAGES-MISSING-KIDS-ENTRY
  #:PAGE-CANNOT-FIND-OBJECT
  #:PAGE-CANNOT-GET-ROOT-PAGES
  #:PAGE-CANNOT-RESTORE-GSTATE
  #:PAGE-CANNOT-SET-PARENT
  #:PAGE-FONT-NOT-FOUND
  #:PAGE-INVALID-FONT
  #:PAGE-INVALID-FONT-SIZE
  #:PAGE-INVALID-GMODE
  #:PAGE-INVALID-INDEX
  #:PAGE-INVALID-ROTATE-VALUE
  #:PAGE-INVALID-SIZE
  #:PAGE-INVALID-XOBJECT
  #:PAGE-OUT-OF-RANGE
  #:REAL-OUT-OF-RANGE
  #:STREAM-EOF
  #:STREAM-READLN-CONTINUE
  #:STRING-OUT-OF-RANGE
  #:THIS-FUNC-WAS-SKIPPED
  #:TTF-CANNOT-EMBED-FONT
  #:TTF-INVALID-CMAP
  #:TTF-INVALID-FORMAT
  #:TTF-MISSING-TABLE
  #:UNSUPPORTED-FONT-TYPE
  #:UNSUPPORTED-JPEG-FORMAT
  #:UNSUPPORTED-TYPE1-FONT
  #:XREF-COUNT-ERR
  #:ZLIB-ERROR
  #:INVALID-PAGE-INDEX
  #:INVALID-URI
  #:PAGE-LAYOUT-OUT-OF-RANGE
  #:PAGE-MODE-OUT-OF-RANGE
  #:PAGE-NUM-STYLE-OUT-OF-RANGE
  #:ANNOT-INVALID-ICON
  #:ANNOT-INVALID-BORDER-STYLE
  #:PAGE-INVALID-DIRECTION
  #:PAGE-INSUFFICIENT-SPACE
  #:PAGE-INVALID-DISPLAY-TIME
  #:PAGE-INVALID-TRANSITION-TIME
  #:INVALID-PAGE-SLIDESHOW-TYPE
  #:EXT-GSTATE-OUT-OF-RANGE
  #:INVALID-EXT-GSTATE
  #:EXT-GSTATE-READ-ONLY
  #:INVALID-ICC-COMPONENT-NUM
  #:PAGE-INVALID-BOUNDARY
  #:INVALID-SHADING-TYPE

  ;; geometry_defines.lsp
  ;; LineCap
  #:BUTT-CAP
  #:ROUND-CAP
  #:PROJECTING-SQUARE-CAP

  ;; geometry_defines.lsp
  ;; LineJoin
  #:MITER-JOIN
  #:ROUND-JOIN
  #:BEVEL-JOIN

  ;; geometry_defines.lsp
  ;; ColorSpace
  #:COLORSPACE-DEVICEGRAY
  #:COLORSPACE-DEVICERGB
  #:COLORSPACE-DEVICECMYK
  #:COLORSPACE-CALGRAY
  #:COLORSPACE-CALRGB
  #:COLORSPACE-LAB
  #:COLORSPACE-ICCBASED
  #:COLORSPACE-SEPARATION
  #:COLORSPACE-DEVICEN
  #:COLORSPACE-INDEXED
  #:COLORSPACE-PATTERN

  ;; geometry_defines.lsp
  ;; BorderStyle
  #:BORDERSTYLE-SOLID
  #:BORDERSTYLE-DASHED
  #:BORDERSTYLE-BEVELED
  #:BORDERSTYLE-INSET
  #:BORDERSTYLE-UNDERLINED

  ;; geometry_defines.lsp
  ;; BlendMode
  #:BLENDMODE-NORMAL
  #:BLENDMODE-COMPATIBLE
  #:BLENDMODE-MULTIPLY
  #:BLENDMODE-SCREEN
  #:BLENDMODE-OVERLAY
  #:BLENDMODE-DARKEN
  #:BLENDMODE-LIGHTEN
  #:BLENDMODE-COLOR-DODGE
  #:BLENDMODE-COLOR-BURN
  #:BLENDMODE-HARD-LIGHT
  #:BLENDMODE-SOFT-LIGHT
  #:BLENDMODE-DIFFERENCE
  #:BLENDMODE-EXCLUSION

  ;; page.lsp
  ;; PageTransition
  #:PAGE-TRANSITION-WIPE-RIGHT
  #:PAGE-TRANSITION-WIPE-UP
  #:PAGE-TRANSITION-WIPE-LEFT
  #:PAGE-TRANSITION-WIPE-DOWN
  #:PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-OUT
  #:PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-IN
  #:PAGE-TRANSITION-BARN-DOORS-VERTICAL-OUT
  #:PAGE-TRANSITION-BARN-DOORS-VERTICAL-IN
  #:PAGE-TRANSITION-BOX-OUT
  #:PAGE-TRANSITION-BOX-IN
  #:PAGE-TRANSITION-BLINDS-HORIZONTAL
  #:PAGE-TRANSITION-BLINDS-VERTICAL
  #:PAGE-TRANSITION-DISSOLVE
  #:PAGE-TRANSITION-GLITTER-RIGHT
  #:PAGE-TRANSITION-GLITTER-DOWN
  #:PAGE-TRANSITION-GLITTER-TOP-LEFT-TO-BOTTOM-RIGHT
  #:PAGE-TRANSITION-REPLACE

  ;; page.lsp
  ;; PageOrientation
  #:PAGE-ORIENTATION-PORTRAIT
  #:PAGE-ORIENTATION-LANDSCAPE

  ;; page.lsp
  ;; PageMode
  #:PAGE-MODE-USE-NONE
  #:PAGE-MODE-USE-OUTLINE
  #:PAGE-MODE-USE-THUMBS
  #:PAGE-MODE-FULL-SCREEN
  #:PAGE-MODE-USE-OC
  #:PAGE-MODE-USE-ATTACHMENTS

  ;; page.lsp
  ;; PageNum
  #:PAGE-NUM-DECIMAL
  #:PAGE-NUM-UPPER-ROMAN
  #:PAGE-NUM-LOWER-ROMAN
  #:PAGE-NUM-UPPER-LETTERS
  #:PAGE-NUM-LOWER-LETTERS

  ;; page.lsp
  ;; PageLayout
  #:PAGE-LAYOUT-SINGLE
  #:PAGE-LAYOUT-ONE-COLUMN
  #:PAGE-LAYOUT-TWO-COLUMN-LEFT
  #:PAGE-LAYOUT-TWO-COLUMN-RIGHT
  #:PAGE-LAYOUT-TWO-PAGE-LEFT
  #:PAGE-LAYOUT-TWO-PAGE-RIGHT

  ;; page.lsp
  ;; PageBoundary
  #:PAGE-MEDIABOX
  #:PAGE-CROPBOX
  #:PAGE-BLEEDBOX
  #:PAGE-TRIMBOX
  #:PAGE-ARTBOX

  ;; text_defines.lsp
  ;; TextAlignment
  #:TEXT-ALIGN-LEFT
  #:TEXT-ALIGN-RIGHT
  #:TEXT-ALIGN-CENTER
  #:TEXT-ALIGN-JUSTIFY

  ;; text_defines.lsp
  ;; TextRenderingMode
  #:TEXT-RENDERING-MODE-FILL
  #:TEXT-RENDERING-MODE-STROKE
  #:TEXT-RENDERING-MODE-FILL-THEN-STROKE
  #:TEXT-RENDERING-MODE-INVISIBLE
  #:TEXT-RENDERING-MODE-FILL-CLIPPING
  #:TEXT-RENDERING-MODE-STROKE-CLIPPING
  #:TEXT-RENDERING-MODE-FILL-STROKE-CLIPPING
  #:TEXT-RENDERING-MODE-CLIPPING

  ;; text_defines.lsp
  ;; WritingMode
  #:WRITING-MODE-HORIZONTAL
  #:WRITING-MODE-VERTICAL

  ;; Page sizes
  ;; ==========
  #:PAGE-SIZE-US-LETTER
  #:PAGE-SIZE-US-LEGAL
  #:PAGE-SIZE-US-TABLOID
  #:PAGE-SIZE-US-LEDGER
  #:PAGE-SIZE-US-JUNIOR-LEGAL
  #:PAGE-SIZE-US-HALF-LETTER
  #:PAGE-SIZE-US-GOVERNMENT-LETTER
  #:PAGE-SIZE-US-GOVERNMENT-LEGAL
  #:PAGE-SIZE-US-ANSI-A
  #:PAGE-SIZE-US-ANSI-B
  #:PAGE-SIZE-US-ANSI-C
  #:PAGE-SIZE-US-ANSI-D
  #:PAGE-SIZE-US-ANSI-E
  #:PAGE-SIZE-US-ARCH-A
  #:PAGE-SIZE-US-ARCH-B
  #:PAGE-SIZE-US-ARCH-C
  #:PAGE-SIZE-US-ARCH-D
  #:PAGE-SIZE-US-ARCH-E
  #:PAGE-SIZE-US-ARCH-E1
  #:PAGE-SIZE-US-ARCH-E2
  #:PAGE-SIZE-US-ARCH-E3
  #:PAGE-SIZE-4A0
  #:PAGE-SIZE-2A0
  #:PAGE-SIZE-A0
  #:PAGE-SIZE-A0-PLUS
  #:PAGE-SIZE-A1
  #:PAGE-SIZE-A1-PLUS
  #:PAGE-SIZE-A2
  #:PAGE-SIZE-A3
  #:PAGE-SIZE-A3-PLUS
  #:PAGE-SIZE-A4
  #:PAGE-SIZE-A5
  #:PAGE-SIZE-A6
  #:PAGE-SIZE-A7
  #:PAGE-SIZE-A8
  #:PAGE-SIZE-A9
  #:PAGE-SIZE-A10
  #:PAGE-SIZE-B0
  #:PAGE-SIZE-B0-PLUS
  #:PAGE-SIZE-B1
  #:PAGE-SIZE-B1-PLUS
  #:PAGE-SIZE-B2
  #:PAGE-SIZE-B2-PLUS
  #:PAGE-SIZE-B3
  #:PAGE-SIZE-B4
  #:PAGE-SIZE-B5
  #:PAGE-SIZE-B6
  #:PAGE-SIZE-B7
  #:PAGE-SIZE-B8
  #:PAGE-SIZE-B9
  #:PAGE-SIZE-B10
  #:PAGE-SIZE-B11
  #:PAGE-SIZE-B12
  #:PAGE-SIZE-B13
  #:PAGE-SIZE-C0
  #:PAGE-SIZE-C1
  #:PAGE-SIZE-C2
  #:PAGE-SIZE-C3
  #:PAGE-SIZE-C4
  #:PAGE-SIZE-C5
  #:PAGE-SIZE-C6
  #:PAGE-SIZE-C7
  #:PAGE-SIZE-C8
  #:PAGE-SIZE-C9
  #:PAGE-SIZE-C10
  #:PAGE-SIZE-BRITISH-DUKES
  #:PAGE-SIZE-BRITISH-FOOLSCAP
  #:PAGE-SIZE-BRITISH-IMPERIAL
  #:PAGE-SIZE-BRITISH-KINGS
  #:PAGE-SIZE-BRITISH-QUARTO
  #:PAGE-SIZE-US-ENVELOPE-6-1-4
  #:PAGE-SIZE-US-ENVELOPE-6-3-4
  #:PAGE-SIZE-US-ENVELOPE-7
  #:PAGE-SIZE-US-ENVELOPE-7-3-4-MONARCH
  #:PAGE-SIZE-US-ENVELOPE8-5-8
  #:PAGE-SIZE-US-ENVELOPE-9
  #:PAGE-SIZE-US-ENVELOPE-10
  #:PAGE-SIZE-US-ENVELOPE-11
  #:PAGE-SIZE-US-ENVELOPE-12
  #:PAGE-SIZE-US-ENVELOPE-14
  #:PAGE-SIZE-US-ENVELOPE-16
  #:PAGE-SIZE-US-ENVELOPE-A1
  #:PAGE-SIZE-US-ENVELOPE-A2-LADY-GREY
  #:PAGE-SIZE-US-ENVELOPE-A4
  #:PAGE-SIZE-US-ENVELOPE-A6-THOMPSON-S-STANDARD
  #:PAGE-SIZE-US-ENVELOPE-A7-BESSELHEIM
  #:PAGE-SIZE-US-ENVELOPE-A8-CARR-S
  #:PAGE-SIZE-US-ENVELOPE-A9-DIPLOMAT
  #:PAGE-SIZE-US-ENVELOPE-A10-WILLOW
  #:PAGE-SIZE-US-ENVELOPE-A-LONG
  #:PAGE-SIZE-US-ENVELOPE-1
  #:PAGE-SIZE-US-ENVELOPE-1-3-4
  #:PAGE-SIZE-US-ENVELOPE-3
  #:PAGE-SIZE-US-ENVELOPE-6
  #:PAGE-SIZE-US-ENVELOPE-8
  #:PAGE-SIZE-US-ENVELOPE-9-3-4
  #:PAGE-SIZE-US-ENVELOPE-10-1-2
  #:PAGE-SIZE-US-ENVELOPE-12-1-2
  #:PAGE-SIZE-US-ENVELOPE-13-1-2
  #:PAGE-SIZE-US-ENVELOPE-14-1-2
  #:PAGE-SIZE-US-ENVELOPE-15
  #:PAGE-SIZE-US-ENVELOPE-15-1-2
  #:PAGE-SIZE-ENVELOPE-DL
  #:PAGE-SIZE-ENVELOPE-B4
  #:PAGE-SIZE-ENVELOPE-B5
  #:PAGE-SIZE-ENVELOPE-B6
  #:PAGE-SIZE-ENVELOPE-C3
  #:PAGE-SIZE-ENVELOPE-C4
  #:PAGE-SIZE-ENVELOPE-C4M
  #:PAGE-SIZE-ENVELOPE-C5
  #:PAGE-SIZE-ENVELOPE-C6-C5
  #:PAGE-SIZE-ENVELOPE-C6
  #:PAGE-SIZE-ENVELOPE-C64M
  #:PAGE-SIZE-ENVELOPE-C7-C6
  #:PAGE-SIZE-ENVELOPE-C7
  #:PAGE-SIZE-ENVELOPE-CE4
  #:PAGE-SIZE-ENVELOPE-CE64
  #:PAGE-SIZE-ENVELOPE-E4
  #:PAGE-SIZE-ENVELOPE-EC45
  #:PAGE-SIZE-ENVELOPE-EC5
  #:PAGE-SIZE-ENVELOPE-E5
  #:PAGE-SIZE-ENVELOPE-E56
  #:PAGE-SIZE-ENVELOPE-E6
  #:PAGE-SIZE-ENVELOPE-E65
  #:PAGE-SIZE-ENVELOPE-R7
  #:PAGE-SIZE-ENVELOPE-S4
  #:PAGE-SIZE-ENVELOPE-S5
  #:PAGE-SIZE-ENVELOPE-S65
  #:PAGE-SIZE-ENVELOPE-X5
  #:PAGE-SIZE-ENVELOPE-EX5
  #:PAGE-SIZE-PHOTO-PASSPORT
  #:PAGE-SIZE-PHOTO-2R
  #:PAGE-SIZE-PHOTO-LD
  #:PAGE-SIZE-PHOTO-DSC
  #:PAGE-SIZE-PHOTO-3R
  #:PAGE-SIZE-PHOTO-L
  #:PAGE-SIZE-PHOTO-LW
  #:PAGE-SIZE-PHOTO-KGD
  #:PAGE-SIZE-PHOTO-KG
  #:PAGE-SIZE-PHOTO-4R
  #:PAGE-SIZE-PHOTO-2LD
  #:PAGE-SIZE-PHOTO-DSCW
  #:PAGE-SIZE-PHOTO-2L
  #:PAGE-SIZE-PHOTO-5R
  #:PAGE-SIZE-PHOTO-2LW
  #:PAGE-SIZE-PHOTO-6R
  #:PAGE-SIZE-PHOTO-8R
  #:PAGE-SIZE-PHOTO-6P
  #:PAGE-SIZE-PHOTO-6PW
  #:PAGE-SIZE-PHOTO-S8R
  #:PAGE-SIZE-PHOTO-11R
  #:PAGE-SIZE-PHOTO-A3-PLUS
  #:PAGE-SIZE-NEWSPAPER-BERLINER
  #:PAGE-SIZE-NEWSPAPER-BROADSHEET
  #:PAGE-SIZE-NEWSPAPER-US-BROADSHEET
  #:PAGE-SIZE-NEWSPAPER-BRITISH-BROADSHEET
  #:PAGE-SIZE-NEWSPAPER-SOUTH-AFRICAN-BROADSHEET
  #:PAGE-SIZE-NEWSPAPER-CINER
  #:PAGE-SIZE-NEWSPAPER-COMPACT
  #:PAGE-SIZE-NEWSPAPER-NORDISCH
  #:PAGE-SIZE-NEWSPAPER-RHENISH
  #:PAGE-SIZE-NEWSPAPER-SWISS
  #:PAGE-SIZE-NEWSPAPER-TABLOID
  #:PAGE-SIZE-NEWSPAPER-CANADIAN-TABLOID
  #:PAGE-SIZE-NEWSPAPER-NORWEGIAN-TABLOID
  #:PAGE-SIZE-NEWSPAPER-NEW-YOUR-TIMES
  #:PAGE-SIZE-NEWSPAPER-WALL-STREET-JOURNAL
  #:PAGE-SIZE-BOOK-FOLIO
  #:PAGE-SIZE-BOOK-QUARTO
  #:PAGE-SIZE-BOOK-IMPERIAL-OCTAVO
  #:PAGE-SIZE-BOOK-SUPER-OCTAVO
  #:PAGE-SIZE-BOOK-ROYAL-OCTAVO
  #:PAGE-SIZE-BOOK-MEDIUM-OCTAVO
  #:PAGE-SIZE-BOOK-OCTAVO
  #:PAGE-SIZE-BOOK-CROWN-OCTAVO
  #:PAGE-SIZE-BOOK-12MO
  #:PAGE-SIZE-BOOK-16MO
  #:PAGE-SIZE-BOOK-18MO
  #:PAGE-SIZE-BOOK-32MO
  #:PAGE-SIZE-BOOK-48MO
  #:PAGE-SIZE-BOOK-64MO
  #:PAGE-SIZE-BOOK-A-FORMAT
  #:PAGE-SIZE-BOOK-B-FORMAT
  #:PAGE-SIZE-BOOK-C-FORMAT
  #:PAGE-SIZE-BUSINESS-CARD-ISO-216
  #:PAGE-SIZE-BUSINESS-CARD-US-CANADA
  #:PAGE-SIZE-BUSINESS-CARD-EUROPEAN
  #:PAGE-SIZE-BUSINESS-CARD-SCANDINAVIA
  #:PAGE-SIZE-BUSINESS-CARD-CHINA
  #:PAGE-SIZE-BUSINESS-CARD-JAPAN
  #:PAGE-SIZE-BUSINESS-CARD-IRAN
  #:PAGE-SIZE-BUSINESS-CARD-HUNGARY
  #:PAGE-SIZE-BUSINESS-CARD-ISO-7810-ID-1
  #:PAGE-SIZE-RAW-RA0
  #:PAGE-SIZE-RAW-RA1
  #:PAGE-SIZE-RAW-RA2
  #:PAGE-SIZE-RAW-RA3
  #:PAGE-SIZE-RAW-RA4
  #:PAGE-SIZE-RAW-SRA0
  #:PAGE-SIZE-RAW-SRA1
  #:PAGE-SIZE-RAW-SRA2
  #:PAGE-SIZE-RAW-SRA3
  #:PAGE-SIZE-RAW-SRA4
  #:PAGE-SIZE-RAW-SRA1-PLUS
  #:PAGE-SIZE-RAW-SRA2-PLUS
  #:PAGE-SIZE-RAW-SRA3-PLUS
  #:PAGE-SIZE-RAW-SRA3-PLUS-PLUS
  #:PAGE-SIZE-RAW-A0U
  #:PAGE-SIZE-RAW-A1U
  #:PAGE-SIZE-RAW-A2U
  #:PAGE-SIZE-RAW-A3U
  #:PAGE-SIZE-RAW-A4U
  #:PAGE-SIZE-BILLBOARD-1-SHEET
  #:PAGE-SIZE-BILLBOARD-2-SHEET
  #:PAGE-SIZE-BILLBOARD-4-SHEET
  #:PAGE-SIZE-BILLBOARD-6-SHEET
  #:PAGE-SIZE-BILLBOARD-12-SHEET
  #:PAGE-SIZE-BILLBOARD-16-SHEET
  #:PAGE-SIZE-BILLBOARD-32-SHEET
  ;; Skipped in data file
  ;; #:PAGE-SIZE-BILLBOARD-48-SHEET
  ;; #:PAGE-SIZE-BILLBOARD-64-SHEET
  ;; #:PAGE-SIZE-BILLBOARD-96-SHEET
  #:PAGE-SIZE-JAPANESE-JB0
  #:PAGE-SIZE-JAPANESE-JB1
  #:PAGE-SIZE-JAPANESE-JB2
  #:PAGE-SIZE-JAPANESE-JB3
  #:PAGE-SIZE-JAPANESE-JB4
  #:PAGE-SIZE-JAPANESE-JB5
  #:PAGE-SIZE-JAPANESE-JB6
  #:PAGE-SIZE-JAPANESE-JB7
  #:PAGE-SIZE-JAPANESE-JB8
  #:PAGE-SIZE-JAPANESE-JB9
  #:PAGE-SIZE-JAPANESE-JB10
  #:PAGE-SIZE-JAPANESE-JB11
  #:PAGE-SIZE-JAPANESE-JB12
  #:PAGE-SIZE-JAPANESE-SHIROKU-BAN-4
  #:PAGE-SIZE-JAPANESE-SHIROKU-BAN-5
  #:PAGE-SIZE-JAPANESE-SHIROKU-BAN-6
  #:PAGE-SIZE-JAPANESE-KIKU-4
  #:PAGE-SIZE-JAPANESE-KIKU-5
  #:PAGE-SIZE-CANADIAN-P1
  #:PAGE-SIZE-CANADIAN-P2
  #:PAGE-SIZE-CANADIAN-P3
  #:PAGE-SIZE-CANADIAN-P4
  #:PAGE-SIZE-CANADIAN-P5
  #:PAGE-SIZE-CANADIAN-P6
  #:PAGE-SIZE-DIN-D0
  #:PAGE-SIZE-DIN-D1
  #:PAGE-SIZE-DIN-D2
  #:PAGE-SIZE-DIN-D3
  #:PAGE-SIZE-DIN-D4
  #:PAGE-SIZE-DIN-D5
  #:PAGE-SIZE-DIN-D6
  #:PAGE-SIZE-DIN-D7
  #:PAGE-SIZE-DIN-D8
  #:PAGE-SIZE-SIS-E0
  #:PAGE-SIZE-SIS-E1
  #:PAGE-SIZE-SIS-E2
  #:PAGE-SIZE-SIS-E3
  #:PAGE-SIZE-SIS-E4
  #:PAGE-SIZE-SIS-E5
  #:PAGE-SIZE-SIS-E6
  #:PAGE-SIZE-SIS-E7
  #:PAGE-SIZE-SIS-E8
  #:PAGE-SIZE-SIS-E9
  #:PAGE-SIZE-SIS-E10
  #:PAGE-SIZE-SIS-F0
  #:PAGE-SIZE-SIS-F1
  #:PAGE-SIZE-SIS-F2
  #:PAGE-SIZE-SIS-F3
  #:PAGE-SIZE-SIS-F4
  #:PAGE-SIZE-SIS-F5
  #:PAGE-SIZE-SIS-F6
  #:PAGE-SIZE-SIS-F7
  #:PAGE-SIZE-SIS-F8
  #:PAGE-SIZE-SIS-F9
  #:PAGE-SIZE-SIS-F10
  #:PAGE-SIZE-SIS-G0
  #:PAGE-SIZE-SIS-G1
  #:PAGE-SIZE-SIS-G2
  #:PAGE-SIZE-SIS-G3
  #:PAGE-SIZE-SIS-G4
  #:PAGE-SIZE-SIS-G5
  #:PAGE-SIZE-SIS-G6
  #:PAGE-SIZE-SIS-G7
  #:PAGE-SIZE-SIS-G8
  #:PAGE-SIZE-SIS-G9
  #:PAGE-SIZE-SIS-G10
  #:PAGE-SIZE-SIS-D0
  #:PAGE-SIZE-SIS-D1
  #:PAGE-SIZE-SIS-D2
  #:PAGE-SIZE-SIS-D3
  #:PAGE-SIZE-SIS-D4
  #:PAGE-SIZE-SIS-D5
  #:PAGE-SIZE-SIS-D6
  #:PAGE-SIZE-SIS-D7
  #:PAGE-SIZE-SIS-D8
  #:PAGE-SIZE-SIS-D9
  #:PAGE-SIZE-SIS-D10
  #:PAGE-SIZE-COLOMBIAN-CARTA
  #:PAGE-SIZE-COLOMBIAN-EXTRA-TABLOIDE
  #:PAGE-SIZE-COLOMBIAN-OFICIO
  #:PAGE-SIZE-COLOMBIAN-1-8-PLIEGO
  #:PAGE-SIZE-COLOMBIAN-1-4-PLIEGO
  #:PAGE-SIZE-COLOMBIAN-1-2-PLIEGO
  #:PAGE-SIZE-COLOMBIAN-PLIEGO
  #:PAGE-SIZE-CHINESE-D0
  #:PAGE-SIZE-CHINESE-D1
  #:PAGE-SIZE-CHINESE-D2
  #:PAGE-SIZE-CHINESE-D3
  #:PAGE-SIZE-CHINESE-D4
  #:PAGE-SIZE-CHINESE-D5
  #:PAGE-SIZE-CHINESE-D6
  #:PAGE-SIZE-CHINESE-RD0
  #:PAGE-SIZE-CHINESE-RD1
  #:PAGE-SIZE-CHINESE-RD2
  #:PAGE-SIZE-CHINESE-RD3
  #:PAGE-SIZE-CHINESE-RD4
  #:PAGE-SIZE-CHINESE-RD5
  #:PAGE-SIZE-CHINESE-RD6
  #:PAGE-SIZE-TRANSITIONAL-PA0
  #:PAGE-SIZE-TRANSITIONAL-PA1
  #:PAGE-SIZE-TRANSITIONAL-PA2
  #:PAGE-SIZE-TRANSITIONAL-PA3
  #:PAGE-SIZE-TRANSITIONAL-PA4
  #:PAGE-SIZE-TRANSITIONAL-PA5
  #:PAGE-SIZE-TRANSITIONAL-PA6
  #:PAGE-SIZE-TRANSITIONAL-PA7
  #:PAGE-SIZE-TRANSITIONAL-PA8
  #:PAGE-SIZE-TRANSITIONAL-PA9
  #:PAGE-SIZE-TRANSITIONAL-PA10
  #:PAGE-SIZE-TRANSITIONAL-F0
  #:PAGE-SIZE-TRANSITIONAL-F1
  #:PAGE-SIZE-TRANSITIONAL-F2
  #:PAGE-SIZE-TRANSITIONAL-F3
  #:PAGE-SIZE-TRANSITIONAL-F4
  #:PAGE-SIZE-TRANSITIONAL-F5
  #:PAGE-SIZE-TRANSITIONAL-F6
  #:PAGE-SIZE-TRANSITIONAL-F7
  #:PAGE-SIZE-TRANSITIONAL-F8
  #:PAGE-SIZE-TRANSITIONAL-F9
  #:PAGE-SIZE-TRANSITIONAL-F10
  #:PAGE-SIZE-IMPERIAL-ANTIQUARIAN
  #:PAGE-SIZE-IMPERIAL-ATLAS
  #:PAGE-SIZE-IMPERIAL-BRIEF
  #:PAGE-SIZE-IMPERIAL-BROADSHEET
  #:PAGE-SIZE-IMPERIAL-CARTRIDGE
  #:PAGE-SIZE-IMPERIAL-COLUMBIER
  #:PAGE-SIZE-IMPERIAL-COPY-DRAUGHT
  #:PAGE-SIZE-IMPERIAL-CROWN
  #:PAGE-SIZE-IMPERIAL-DEMY
  #:PAGE-SIZE-IMPERIAL-DOUBLE-DEMY
  #:PAGE-SIZE-IMPERIAL-QUAD-DEMY
  #:PAGE-SIZE-IMPERIAL-ELEPHANT
  #:PAGE-SIZE-IMPERIAL-DOUBLE-ELEPHANT
  #:PAGE-SIZE-IMPERIAL-EMPEROR
  #:PAGE-SIZE-IMPERIAL-FOOLSCAP
  #:PAGE-SIZE-IMPERIAL-SMALL-FOOLSCAP
  #:PAGE-SIZE-IMPERIAL-GRAND-EAGLE
  #:PAGE-SIZE-IMPERIAL-IMPERIAL
  #:PAGE-SIZE-IMPERIAL-MEDIUM
  #:PAGE-SIZE-IMPERIAL-MONARCH
  #:PAGE-SIZE-IMPERIAL-POST
  #:PAGE-SIZE-IMPERIAL-HALF-POST
  #:PAGE-SIZE-IMPERIAL-PINCHED-POST
  #:PAGE-SIZE-IMPERIAL-LARGE-POST
  #:PAGE-SIZE-IMPERIAL-DOUBLE-LARGE-POST
  #:PAGE-SIZE-IMPERIAL-DOUBLE-POST
  #:PAGE-SIZE-IMPERIAL-POTT
  #:PAGE-SIZE-IMPERIAL-PRINCESS
  #:PAGE-SIZE-IMPERIAL-QUARTO
  #:PAGE-SIZE-IMPERIAL-ROYAL
  #:PAGE-SIZE-IMPERIAL-SUPER-ROYAL
  #:PAGE-SIZE-FRENCH-CLOCHE
  #:PAGE-SIZE-FRENCH-POT-ECOLIER
  #:PAGE-SIZE-FRENCH-TELLIERE
  #:PAGE-SIZE-FRENCH-COURONNE-ECRITURE
  #:PAGE-SIZE-FRENCH-COURONNE-EDITION
  #:PAGE-SIZE-FRENCH-ROBERTO
  #:PAGE-SIZE-FRENCH-ECU
  #:PAGE-SIZE-FRENCH-COQUILLE
  #:PAGE-SIZE-FRENCH-CARRE
  #:PAGE-SIZE-FRENCH-CAVALIER
  #:PAGE-SIZE-FRENCH-DEMI-RAISIN
  #:PAGE-SIZE-FRENCH-RAISIN
  #:PAGE-SIZE-FRENCH-DOUBLE-RAISIN
  #:PAGE-SIZE-FRENCH-JESUS
  #:PAGE-SIZE-FRENCH-SOLEIL
  #:PAGE-SIZE-FRENCH-COLOMBIER-AFFICHE
  #:PAGE-SIZE-FRENCH-COLOMBIER-COMMERCIAL
  #:PAGE-SIZE-FRENCH-PETIT-AIGLE
  #:PAGE-SIZE-FRENCH-GRAND-AIGLE
  #:PAGE-SIZE-FRENCH-GRAND-MONDE
  #:PAGE-SIZE-FRENCH-UNIVERS
  #:PAGE-SIZE-RUSSIAN-60X84-8
  #:PAGE-SIZE-RUSSIAN-60X84-16
  #:PAGE-SIZE-RUSSIAN-60X84-32
  #:PAGE-SIZE-RUSSIAN-60X90-8
  #:PAGE-SIZE-RUSSIAN-60X90-16
  #:PAGE-SIZE-RUSSIAN-70X100-16
  #:PAGE-SIZE-RUSSIAN-70X100-32
  #:PAGE-SIZE-RUSSIAN-70X108-8
  #:PAGE-SIZE-RUSSIAN-70X108-16
  #:PAGE-SIZE-RUSSIAN-70X108-32
  #:PAGE-SIZE-RUSSIAN-70X90-16
  #:PAGE-SIZE-RUSSIAN-70X90-32
  #:PAGE-SIZE-RUSSIAN-75X90-32
  #:PAGE-SIZE-RUSSIAN-84X108-8
  #:PAGE-SIZE-RUSSIAN-84X108-32

  ;; Macro
  ;; =====
  #:page-set-dash-pattern
  #:stream-set-dash-pattern
  #:with-page-gsave
  #:with-pdf-document
  #:with-stream-gsave
  #:with-ttf-font
  #:string-to-cstring
)
(:shadow :REAL :BYTE :Error :Array :PI))

